module.exports = {
    // Possible Errors
    "for-direction": 2,
    "getter-return": 2,
    "no-async-promise-executor": 2,
    "no-compare-neg-zero": 2,
    "no-case-declarations": 2,
    "no-class-assign": 2,
    "no-cond-assign": 2,
    "no-constant-condition": 1,
    "no-control-regex": 2,
    "no-debugger": 0,
    "no-dupe-args": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty": 2,
    "no-empty-character-class": 0,
    "no-ex-assign": 2,
    "no-extra-boolean-cast": 0,
    "no-extra-semi": 1,
    "no-func-assign": 1,
    "no-inner-declarations": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 1,
    "no-misleading-character-class": 0,
    "no-obj-calls": 2,
    "no-prototype-builtins": 0,
    "no-regex-spaces": 1,
    "no-sparse-arrays": 1,

    // Best Practices
    "no-empty-pattern": 1,
    "no-fallthrough": 2,
    "no-global-assign": 2,
    "no-octal": 0,
    "no-redeclare": 2,
    "no-self-assign": 0,
    "no-unexpected-multiline": 1,
    "no-unreachable": 2,
    "no-unsafe-finally": 1,
    "no-unsafe-negation": 0,
    "no-unused-labels": 0,
    "no-useless-catch": 0,
    "no-useless-escape": 0,
    "no-with": 2,
    "use-isnan": 2,
    "valid-typeof": 0,
    
    // Variables
    "no-delete-var": 0,
    "no-shadow-restricted-names": 2,
    "no-undef": 2,
    "no-unused-vars": 2,

    // Stylistic Issues
    "no-mixed-spaces-and-tabs": 0,

    // ECMAScript 6
    "constructor-super": 1,
    "no-const-assign": 2,
    "no-dupe-class-members": 2,
    "no-new-symbol": 0,
    "no-this-before-super": 2,
    "require-yield": 2
}